### PR TITLE
Fixes for crash and client not updating auth state

### LINKED ISSUE #206: Newly logged in client marbles not recognised
**Expected behavior**
When a client logs in and enters a race, the client's marble is highlighted and/or tracked with the tracking camera.

**Actual behavior**
The client's added marble is not treated as the client's marble (no different name colour or camera tracking), until the client refreshes the page.

**Reproduction steps**
1. Ensure you are logged out and have refreshed the page.
2. Log in.
3. Type `!marble` or click the button that does this for you.
4. The marble entered has the same appearance as any other marble until you refresh.

**Additional context**
Likely, similar issues will occur if a client logs out and logs back in on a different account.
This bug may also be related to #193 to some extent.

### PR DESCRIPTION
**Pull request by Zemanzo**
- Crash due to cookie not being the right format.
- Client authorization state is now updated on log in and log out. This allows the player's marble to be tracked automatically without refresh.

Closes #206 

This can still be improved to also update the marble sprite halfway the race, but this is good enough for now.

PS: also added a comment somewhere because I thought it could use it there c:

### CODE REVIEW

File: src/client/user-state.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
+import * as Cookies from "js-cookie";
+
+window.addEventListener("message", function(event) {
+	// Don't parse anything that isn't ours
+	if (event.origin !== window.location.origin) return;
+
+	// If the authorization state has changed, update the user data
+	if (event.data === userState.AUTH_CHANGED) {
+		userState.data = Cookies.getJSON("user_data");
+		console.log("updated user_data", userState.data);
```
Comment (Qaomen) [inline src/client/user-state.js]: Leftover logging?

**Review by Qaomen — CHANGES_REQUESTED** [review]
Good to see the user data in one place! Just a little leftover logging and then it's ready to be merged.

**Review by Qaomen — APPROVED** [review]
